// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bDItGYp2efrWR4y9YcpBOFscw84P1Rg',
    appId: '1:60430010007:web:dda3195cd00f649d80cbd2',
    messagingSenderId: '60430010007',
    projectId: 'flutter-login-bc9cc',
    authDomain: 'flutter-login-bc9cc.firebaseapp.com',
    storageBucket: 'flutter-login-bc9cc.appspot.com',
    measurementId: 'G-XMWFZ3WKME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkw8LrfLSZRlEfZ1dmvnaUC7uFuIqr1Tk',
    appId: '1:60430010007:android:0addbcd01d7d310780cbd2',
    messagingSenderId: '60430010007',
    projectId: 'flutter-login-bc9cc',
    storageBucket: 'flutter-login-bc9cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZUJzajzPolK-fXveWP6GGxRHTpF1Uo4',
    appId: '1:60430010007:ios:66fc05da67fcc7b580cbd2',
    messagingSenderId: '60430010007',
    projectId: 'flutter-login-bc9cc',
    storageBucket: 'flutter-login-bc9cc.appspot.com',
    androidClientId: '60430010007-o97freuafqeitfe6ff5kialqc8mv3act.apps.googleusercontent.com',
    iosClientId: '60430010007-rqacptviujogogre9tkg71u4jobtunj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ks3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbZUJzajzPolK-fXveWP6GGxRHTpF1Uo4',
    appId: '1:60430010007:ios:66fc05da67fcc7b580cbd2',
    messagingSenderId: '60430010007',
    projectId: 'flutter-login-bc9cc',
    storageBucket: 'flutter-login-bc9cc.appspot.com',
    androidClientId: '60430010007-o97freuafqeitfe6ff5kialqc8mv3act.apps.googleusercontent.com',
    iosClientId: '60430010007-rqacptviujogogre9tkg71u4jobtunj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ks3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7bDItGYp2efrWR4y9YcpBOFscw84P1Rg',
    appId: '1:60430010007:web:ac732ee4b45d5f7680cbd2',
    messagingSenderId: '60430010007',
    projectId: 'flutter-login-bc9cc',
    authDomain: 'flutter-login-bc9cc.firebaseapp.com',
    storageBucket: 'flutter-login-bc9cc.appspot.com',
    measurementId: 'G-J6D3304MTL',
  );
}
